# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshh < Formula
  desc "TUI for managing SSH servers and tunnels"
  homepage "https://github.com/nakulmanimala/sshh"
  version "1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nakulmanimala/sshh/releases/download/v1.3/sshh_Darwin_x86_64.tar.gz"
      sha256 "93bca41bef773554d221f4b7e5465955d295b3bf2975247218c34f7b72b8311f"

      define_method(:install) do
        bin.install "sshh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nakulmanimala/sshh/releases/download/v1.3/sshh_Darwin_arm64.tar.gz"
      sha256 "a51c7bd5898644c6b84e88d400cf827259375db717ccc396f1603c4a039ea4a4"

      define_method(:install) do
        bin.install "sshh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nakulmanimala/sshh/releases/download/v1.3/sshh_Linux_x86_64.tar.gz"
      sha256 "06488ad1bcc99063bdf47a9bf0dfdae72d53991cf2d0b23660fcc9d75ac16c5c"
      define_method(:install) do
        bin.install "sshh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nakulmanimala/sshh/releases/download/v1.3/sshh_Linux_arm64.tar.gz"
      sha256 "90446b6e490d2dc2510dab12d1b10bd72ca6d2f915a5805d250985ed55efc287"
      define_method(:install) do
        bin.install "sshh"
      end
    end
  end
end
